ath6kl: Do not use virt_addr_valid()
virt_addr_valid() doesn't seem to be meant for drivers to use, and
currently cannot be used from modules on MIPS:

ERROR: "min_low_pfn" [drivers/net/wireless/ath/ath6kl/ath6kl_sdio.ko] undefined!

Instead of trying to check the given pointer, split
ath6kl_sdio_read_write_sync() into two functions:
__ath6kl_sdio_read_write_sync() takes an explicit 'may_dma' parameter
and ath6kl_sdio_read_write_sync() is a wrapper that passes false.
Make __ath6kl_sdio_write_async() pass true since we know it always has
a heap-allocated buffer and it's the one case where the performance
benefit of DMA matters.